---
title: "Hands-on Exercise 5A: Global Measures of Spatial Autocorrelation"
date: "September 17, 2026"
date-modified: "last-modified"
format: html
execute:
  echo: true
  eval: true
  message: false
  warning: false
  freeze: true
editor: visual
---

# 9.2 Getting Started

```{r}
pacman::p_load(sf, spdep, tmap, tidyverse)
```

# 9.3 Getting the Data Into R Environment

```{r}
# Import shapefile into r environment

hunan <- st_read(dsn = "data/geospatial", 
                 layer = "Hunan")

# Import csv file into r environment

hunan2012 <- read_csv("data/aspatial/Hunan_2012.csv")

# Performing relational join

hunan <- left_join(hunan,hunan2012) %>%
  select(1:4, 7, 15)

# Visualising Regional Development Indicator

equal <- tm_shape(hunan) +
  tm_polygons(fill = "GDPPC",
              fill.scale = tm_scale_intervals(
                style = "equal",
                n = 5,
                values = "brewer.blues")) +
  tm_borders(fiil_alpha = 0.5) + 
  tm_layout(legend.position = c("left", "bottom"), 
            main.title = "Equal interval classification")

quantile <- tm_shape(hunan) +
  tm_polygons(fill = "GDPPC",
              fill.scale = tm_scale_intervals(
                style = "quantile",
                n = 5)) +
  tm_borders(fiil_alpha = 0.5) + 
  tm_layout(legend.position = c("left", "bottom"), 
            main.title = "Quantile classification")

tmap_arrange(equal, 
             quantile, 
             asp=1, 
             ncol=2)
```

# 9.4 Global Measures of Spatial Autocorrelation

```{r}
# Computing Contiguity Spatial Weights

wm_q <- poly2nb(hunan, 
                queen=TRUE)
summary(wm_q)

# Row-standardised weights matrix

rswm_q <- nb2listw(wm_q, 
                   style="W", 
                   zero.policy = TRUE)
rswm_q
```

# 9.5 Global Measures of Spatial Autocorrelation: Moran’s I

```{r}
# Maron’s I test

moran.test(hunan$GDPPC, 
           listw=rswm_q, 
           zero.policy = TRUE, 
           na.action=na.omit)

# Computing Monte Carlo Moran’s I

set.seed(1234)
bperm= moran.mc(hunan$GDPPC, 
                listw=rswm_q, 
                nsim=999, 
                zero.policy = TRUE, 
                na.action=na.omit)
bperm

# Visualising Monte Carlo Moran’s I

mean(bperm$res[1:999])

var(bperm$res[1:999])

summary(bperm$res[1:999])

hist(bperm$res, 
     freq=TRUE, 
     breaks=20, 
     xlab="Simulated Moran's I")
abline(v=0, 
       col="red") 
```

# 9.6 Global Measures of Spatial Autocorrelation: Geary’s C

```{r}
# Geary’s C test

geary.test(hunan$GDPPC, listw=rswm_q)

# Computing Monte Carlo Geary’s C

set.seed(1234)
bperm=geary.mc(hunan$GDPPC, 
               listw=rswm_q, 
               nsim=999)
bperm

# Visualising the Monte Carlo Geary’s C

mean(bperm$res[1:999])

var(bperm$res[1:999])

summary(bperm$res[1:999])

hist(bperm$res, freq=TRUE, breaks=20, xlab="Simulated Geary c")
abline(v=1, col="red") 
```

# 9.7 Spatial Correlogram

```{r}
# Compute Moran’s I correlogram

MI_corr <- sp.correlogram(wm_q, 
                          hunan$GDPPC, 
                          order=6, 
                          method="I", 
                          style="W")
plot(MI_corr)

print(MI_corr)

# Compute Geary’s C correlogram and plot

GC_corr <- sp.correlogram(wm_q, 
                          hunan$GDPPC, 
                          order=6, 
                          method="C", 
                          style="W")
plot(GC_corr)

print(GC_corr)
```
