---
title: "Hands-on Exercise 5B: Local Measures of Spatial Autocorrelation"
date: "September 17, 2026"
date-modified: "last-modified"
format: html
execute:
  echo: true
  eval: true
  message: false
  warning: false
  freeze: true
editor: visual
---

# 10.2 Getting Started

```{r}
pacman::p_load(sf, sfdep, tmap, tidyverse)
```

# 10.3 Getting the Data Into R Environment

```{r}
# Import shapefile into r environment

hunan <- st_read(dsn = "data/geospatial", 
                 layer = "Hunan") %>% 
  st_transform(crs = 32650)

# Import csv file into r environment

hunan2012 <- read_csv("data/aspatial/Hunan_2012.csv")

# Performing relational join

hunan <- left_join(hunan,hunan2012) %>%
  select(1:4, 7, 15)

# Visualising Regional Development Indicator

equal <- tm_shape(hunan) +
  tm_polygons(fill = "GDPPC",
              fill.scale = tm_scale_intervals(
                style = "equal",
                n = 5,
                values = "brewer.blues"),
              fill.legend = tm_legend(
                title = "GDPPC",
                position = tm_pos_in(
                  "left", "bottom"))) + 
  tm_borders(fill_alpha = 0.5) +
  tm_title("Equal interval classification")

quantile <- tm_shape(hunan) +
  tm_polygons(fill = "GDPPC",
              fill.scale = tm_scale_intervals(
                style = "quantile",
                n = 5,
                values = "brewer.blues"),
              fill.legend = tm_legend(
                title = "GDPPC",
                position = tm_pos_in(
                  "left", "bottom"))) + 
  tm_borders(fill_alpha = 0.5) +
  tm_title("Quantile interval classification")

tmap_arrange(equal, 
             quantile, 
             asp=1, 
             ncol=2)
```

# 10.4 Local Indicators of Spatial Association(LISA)

```{r}
# Computing Contiguity Spatial Weights

wm_q <- hunan %>%
  mutate(nb = st_contiguity(geometry),
         wt = st_weights(
           nb, style = "W"),
         .before = 1) 

summary(wm_q$nb)

# Computing local Moran’s I

set.seed(1234)

lisa <- wm_q %>% 
  mutate(local_moran = local_moran(
    GDPPC, nb, wt, nsim = 99),
    .before = 1) %>%
  unnest(local_moran)

glimpse(lisa)

tm_shape(lisa) +
  tm_polygons(fill = "ii",
              fill.scale = tm_scale_intervals(
                style = "pretty",
                n = 5,
                values = "brewer.RdBu"),
              fill.legend = tm_legend(
                title = "Local Morans'I",
                position = tm_pos_out())) + 
  tm_borders(fill_alpha = 0.5) +
  tm_title("Loal Morans'I of GDPPC (Queen's method)")

tm_shape(lisa) +
  tm_polygons(fill = "p_ii", 
              fill.scale = tm_scale_intervals(
                breaks = c(-Inf, 0.001, 0.01, 0.05, 0.1, Inf),
                values = "-brewer.Reds"),
              fill.legend = tm_legend(
                title = "p-value",
                position = tm_pos_out())) + 
  tm_borders(fill_alpha = 0.5) +
  tm_title("p-values of Loal Moran's I of GDPPC (Queen's method)")

ii.map <- tm_shape(lisa) +
  tm_polygons(fill = "ii",
              fill.scale = tm_scale_intervals(
                style = "pretty",
                n = 5,
                values = "brewer.RdBu"),
              fill.legend = tm_legend(
                title = "Local Moran's I",
                position = tm_pos_in(
                  "left", "bottom"))) + 
  tm_borders(fill_alpha = 0.5) +
  tm_title("Loal Moran's I of GDPPC (Queen's method)")

p_ii.map <- tm_shape(lisa) +
  tm_polygons(fill = "p_ii", 
              fill.scale = tm_scale_intervals(
                breaks = c(-Inf, 0.001, 0.01, 0.05, 0.1, Inf),
                values = "-brewer.Reds"),
              fill.legend = tm_legend(
                title = "p-value",
                position = tm_pos_in("left", "bottom")
              )) + 
  tm_borders(fill_alpha = 0.5) +
  tm_title("p-values of Loal Moran's I of GDPPC (Queen's method)")

tmap_arrange(ii.map, p_ii.map, asp=1, ncol=2)

# Preparing and Visualising LISA Map

lisa <- lisa %>%
  mutate(lag_GDPPC = st_lag(
    GDPPC, nb, wt),
    .before = 1) %>%
  unnest(lag_GDPPC)

ggplot(data = lisa, 
       aes(x = GDPPC, 
           y = lag_GDPPC)) +
  geom_point() +
  geom_smooth(method = "lm", 
              se = FALSE, 
              color = "red") +
  labs(x = "GDPPC",
       y = "Spatial Lag of GDPPC",
       title = "Moran Scatterplot") +
  theme_minimal()

ggplot(data = lisa, 
       aes(x = GDPPC, 
           y = lag_GDPPC, 
           color = mean)) +
  geom_point(size = 2) +
  geom_smooth(method = "lm", 
              se = FALSE, 
              color = "black") +
  geom_hline(yintercept=mean(lisa$lag_GDPPC), lty=2) + 
  geom_vline(xintercept=mean(lisa$GDPPC), lty=2) +
  scale_color_manual(
    values = c("High-High" = "red", 
               "Low-Low" = "blue",
               "Low-High" = "lightblue", 
               "High-Low" = "pink")) +
  labs(x = "GDPPC",
       y = "Spatial Lag of GDPPC",
       title = "Moran Scatterplot with LISA Quadrants") +
  theme_minimal()

lisa <- lisa %>%
  mutate(z_GDPPC = scale(GDPPC),
         z_lag_GDPPC = scale(lag_GDPPC),
         .before = 1)

ggplot(data = lisa, 
       aes(x = z_GDPPC, 
           y = z_lag_GDPPC, 
           color = mean)) +
  geom_point(size = 2) +
  geom_smooth(method = "lm", 
              se = FALSE, 
              color = "black") +
  geom_hline(yintercept=mean(lisa$z_lag_GDPPC), lty=2) + 
  geom_vline(xintercept=mean(lisa$z_GDPPC), lty=2) +
  scale_color_manual(
    values = c("High-High" = "red", 
               "Low-Low" = "blue",
               "Low-High" = "lightblue", 
               "High-Low" = "pink")) +
  labs(x = "Standardised GDPPC",
       y = "Standardised Spatial Lag of GDPPC",
       title = "Standardised Moran Scatterplot with LISA Quadrants") +
  theme_minimal()

signif <- 0.05       

lisa <- lisa %>%
  mutate(
    LISA_cluster = ifelse(
      p_ii < 0.05,
      as.character(mean), 
      "Insignificant"),
    LISA_cluster = factor(
      LISA_cluster,
      levels = c("Insignificant", "Low-Low", "Low-High", "High-Low", "High-High")
    )
  )

lisa_map <- tm_shape(lisa) + 
  tm_polygons(
    fill = "LISA_cluster",
    fill.scale = tm_scale_categorical(
      values = c(
        "grey80",      # Insignificant
        "blue",        # Low-Low
        "lightblue",   # Low-High
        "pink",        # High-Low
        "red"          # High-High
      )
    ),
    fill.legend = tm_legend(
      title = "LISA Cluster",
      position = tm_pos_in("left", "bottom"))
  ) +
  tm_borders() +
  tm_title("Local Moran's I Clusters (p < 0.05)")
lisa_map
```

# 10.5 Hot Spots and Cold Spots Analysis (HCSA)

```{r}
# Deriving distance weight matrix

ct <- critical_threshold(st_geometry(hunan))
ct

hunan_fdw <- hunan %>% 
  mutate(nb = include_self(
    st_dist_band(
      st_geometry(geometry), 
      upper = ct)),
    wt = st_weights(nb, 
                    style = "W"),
    .before = 1) 

hunan_adw <- hunan %>%
  mutate(nb = include_self(
    st_knn(
      st_geometry(geometry),
      k = 6)),
    wt = st_weights(
      nb, style = "W"),
    .before = 1)

# Computing local Gi*

HCSA_fdw <- hunan_fdw %>%
  mutate(
    gistar = local_gstar_perm(
      GDPPC, nb, wt, nsim = 99),
    .before = 1) %>%
  unnest(gistar)

# Preparing and Visualising HCSA Map

tm_shape(HCSA_fdw) +
  tm_polygons(fill = "gi_star",
              fill.scale = tm_scale_intervals(
                style = "pretty",
                n = 6,
                values = "brewer.rd_bu"),
              fill.legend = tm_legend(
                title = "Gi*",
                position = tm_pos_out())) + 
  tm_borders(fill_alpha = 0.5) +
  tm_title("Gi* of GDPPC (Fixed Bandwidth d = 60799.91m)")

tm_shape(HCSA_fdw) +
  tm_polygons(fill = "p_sim", 
              fill.scale = tm_scale_intervals(
                breaks = c(-Inf, 0.001, 0.01, 0.05, 0.1, Inf),
                values = "-brewer.Reds"),
              fill.legend = tm_legend(
                title = "simulated p-value",
                position = tm_pos_out())) + 
  tm_borders(fill_alpha = 0.5) +
  tm_title("p-values of local Gi* of GDPPC (Fixed distance)")

Gi_star_map <- tm_shape(HCSA_fdw) +
  tm_polygons(fill = "gi_star",
              fill.scale = tm_scale_intervals(
                style = "pretty",
                n = 5,
                values = "-brewer.rd_bu"),
              fill.legend = tm_legend(
                title = "local Gi*",
                position = tm_pos_in(
                  "left", "bottom"))) + 
  tm_borders(fill_alpha = 0.5) +
  tm_title("Local Gi* of GDPPC")

p_values_map <- tm_shape(HCSA_fdw) +
  tm_polygons(fill = "p_sim", 
              fill.scale = tm_scale_intervals(
                breaks = c(0, 0.001, 0.01, 0.05, 0.1, 1),
                values = "-brewer.reds"),
              fill.legend = tm_legend(
                title = "p-value",
                position = tm_pos_in("left", "bottom")
              )) + 
  tm_borders(fill_alpha = 0.5) +
  tm_title("p-values of local Gi* of GDPPC (fixed distance)")

tmap_arrange(Gi_star_map, p_values_map, asp=1, ncol=2)

HCSA_fdw <- HCSA_fdw %>%
  mutate(HCSA_cluster = case_when(
    p_sim > 0.05 ~ "Insignificant",
    p_sim <= 0.05 & cluster == "High" ~ "Hot spot",
    p_sim <= 0.05 & cluster == "Low"  ~ "Cold spot",
    TRUE ~ "Other"),
    HCSA_cluster = factor(
      HCSA_cluster,
      levels = c("Insignificant", "Hot spot", "Cold spot")
    ),
    .before = 1
  )

HCSA_map <- tm_shape(HCSA_fdw) + 
  tm_polygons(
    fill = "HCSA_cluster",
    fill.scale = tm_scale_categorical(
      values = c(
        "grey80",      # Insignificant
        "red",        # Low-Low
        "blue"          # High-High
      )
    ),
    fill.legend = tm_legend(
      title = "HSCA Cluster",
      position = tm_pos_in("left", "bottom"))
  ) +
  tm_borders() +
  tm_title("HCSA Clusters (p < 0.05)")
HCSA_map

tmap_arrange(Gi_star_map, HCSA_map, asp=1, ncol=2)
```
