---
title: "In-class Exercise 4 v1"
author: "Murat Kaya"
format: html
date: "September 18, 2026"
date-modified: today
execute:
  echo: true
  eval: true
  warning: false
  freeze: true
  message: false
---

```{r}
pacman::p_load(sf, ggstatsplot, tmap, tidyverse, knitr, GWmodel)
```

```{r}
# Import shapefile into r environment

hunan <- st_read(dsn = "data/geospatial", 
                 layer = "Hunan")

# Import csv file into r environment

hunan2012 <- read_csv("data/aspatial/Hunan_2012.csv")

# Performing relational join

hunan <- left_join(hunan,hunan2012) %>%
  select(1:3, 7, 15, 16, 31, 32)

#Mapping GDPPC

#| fig-width: 16
#| fig-height: 6
#| echo: false
basemap <- tm_shape(hunan) +
  tm_polygons() +
  tm_text("NAME_3", size=0.5)

gdppc <- qtm(hunan, "GDPPC") +
  tm_layout(
    legend.position = c("left", "bottom"))
tmap_arrange(basemap, gdppc, asp=1, ncol=2)

# Converting to SpatialPolygonDataFrame

hunan_sp <- hunan %>%
  as_Spatial()

# Geographically Weighted Summary Statistics (GSWW) with adaptive bandwidth

bw_CV <- bw.gwr(GDPPC ~ 1,
               data = hunan_sp,
               approach = "CV",
               adaptive = TRUE,
               kernel = "bisquare",
               longlat = T)

bw_AIC <- bw.gwr(GDPPC ~ 1,
                data = hunan_sp,
                approach = "AICc",
                adaptive = TRUE,
                kernel = "bisquare",
                longlat = T)

# GWSS with Fixed Bandwidth

bw_CV <- bw.gwr(GDPPC ~ 1,
                data = hunan_sp,
                approach = "CV",
                adaptive = FALSE,
                kernel = "bisquare",
                longlat = T)

# Computing geographically weighted summary statistics

gwstat <- gwss(data = hunan_sp,
               vars = "GDPPC",
               bw = bw_AIC,
               kernel = "bisquare",
               quantile = TRUE,
               adaptive = TRUE,
               longlat = T)

# Preparing the output data

gwstat_df <- as.data.frame(gwstat$SDF)

hunan_gstat <- cbind(hunan, gwstat_df)

# Visualising geographically weighted summary statistics

tm_shape(hunan_gstat) +
  tm_polygons(fill = "GDPPC_LM",
              fill.scale = tm_scale_intervals(
                style = "quantile",
                n = 5,
                values = "brewer.blues"),
              fill.legend = tm_legend(
                title = "local Mean")) +
  tm_borders(fill_alpha = 0.5) +
  tm_title("Distribution of geographically wieghted mean") +
  tm_layout(legend.position = c("left", "bottom"))
```
