{
  "hash": "e8948d639a31ac4e8860c023e60d0a33",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Take-home Exercise 1: Geospatial Analytics for Public Safety\"\nauthor: \"Murat Kaya\"\nformat: html\ndate: \"September 18, 2026\"\ndate-modified: today\nexecute:\n  echo: true\n  eval: true\n  warning: false\n  freeze: true\n  message: false\n---\n\n# Executive Summary\n\n```{=html}\n<a href=\"Executive_Summary_Ex01.html\" target=\"_blank\" rel=\"noopener\">\n  View presentation slides\n</a>\n```\n\n# Setting the Scene\n\nPublic safety concerns the protection of the public, communities, and critical infrastructure from crimes, disasters, accidents, and other major threats through coordinated government and agency action. Geospatial analytics supports this effort by transforming multi-source, location-based data into visual evidence, analytical insights, and decision support across domains such as law enforcement, emergency management, transportation safety, and environmental management.\n\nA spatial point pattern is a collection of locations at which events occur, such as forest-fire detections or road traffic accidents. A spatio-temporal point pattern also records when each event occurs, enabling analysts to examine how events are distributed and interact across both space and time. Understanding where and when such events occur helps planners and managers identify areas of concern, allocate resources, and develop evidence-informed prevention and response strategies.\n\n# Objectives\n\nThis take-home exercise investigates the spatial and/or spatio-temporal patterns of public-safety point events using:\n\n- **Road traffic accidents** within the Bangkok Greater Metropolitan Area for 2022\n\nThe specific objectives are:\n\n- To prepare and integrate real-world geospatial and temporal data for spatial and spatio-temporal point-pattern analysis.\n\n- To investigate first-order properties of the point pattern by examining how the intensity or distribution of events varies across space and/or time.\n\n- To investigate second-order properties by examining whether events exhibit evidence of spatial or spatio-temporal interaction, such as clustering, inhibition, or approximate randomness.\n\n- To critically evaluate the analytical assumptions, methodological choices, and limitations associated with the selected point-pattern methods.\n\n- To communicate the analytical findings effectively through appropriate geovisualisation and geocommunication.\n\n- To translate the analytical evidence into meaningful implications for public-safety planning and management.\n\n# The Data\n\nRecorded road accidents in Thailand from 2022 were used. The data was downloaded from:\n\n<https://www.kaggle.com/datasets/thaweewatboy/thailand-road-accident-2019-2022>\n\nThe Thailand Subnational Administrative Boundaries dataset (geoBoundaries-THA-ADM1.geojson) was downloaded from:\n\n<https://data.humdata.org/dataset/geoboundaries-admin-boundaries-for-thailand>\n\n# Study Design and Assumptions\n\nEach point represents one recorded road traffic accident, identified by acc_code and located using its longitude and latitude. Exact duplicate rows are removed. Separate accidents occurring at the same coordinates are retained because a location can experience multiple accidents.\n\nThe study covers accidents occurring between 1 January and 31 December 2022. Records are selected using the incident date rather than the reporting date, since an accident may be reported later.\n\nThe study area comprises Bangkok, Nonthaburi, Pathum Thani, Samut Prakan, Samut Sakhon and Nakhon Pathom. These six province boundaries define the Bangkok Metropolitan Region observation window. Only accident points within this window are included.\n\nAccident coordinates are treated as WGS 84 (EPSG:4326). Both accident points and boundaries are transformed to UTM Zone 47N (EPSG:32647), allowing distances to be measured in metres. The point-pattern object is subsequently rescaled to kilometres for easier interpretation.\n\nThe analysis assumes that retained coordinates adequately represent accident locations.\n\n# The Tasks\n\n## Task 1: Data Preparation\n\n### **Data Acquisition**\n\n| Item | Thailand Road Accident \\[2019–2022\\] | Thailand Administrative Boundaries |\n|------------------------|------------------------|------------------------|\n| **Source** | [Kaggle: Thailand Road Accident \\[2019–2022\\]](https://www.kaggle.com/datasets/thaweewatboy/thailand-road-accident-2019-2022) | [Humanitarian Data Exchange: Thailand Administrative Boundaries](https://data.humdata.org/dataset/geoboundaries-admin-boundaries-for-thailand), produced by geoBoundaries. |\n| **Date of access** | 24 September 2026. | 24 September 2026. |\n| **Geographic coverage** | Recorded road traffic accidents across Thailand. For this study, records will be restricted to Bangkok, Nonthaburi, Pathum Thani, Samut Prakan, Samut Sakhon and Nakhon Pathom. | Administrative boundaries covering Thailand. The dataset provides ADM1 layer. Province-level boundaries will be used to define the study area. |\n| **Temporal coverage** | The source dataset covers 2019–2022. This study only uses 2022 accident data and retains events occurring between 1 January and 31 December 2022. | A static representation of administrative boundaries. |\n| **Relevant characteristics** | The supplied CSV contains accident-level records with 18 variables. These include accident identifiers, incident and reporting timestamps, province names, reporting agencies, routes, vehicle types, presumed causes, accident types, numbers of vehicles involved, fatalities, injuries, weather conditions, coordinates and road characteristics. Longitude and latitude enable conversion into spatial points. | Vector polygon boundaries available in GeoJSON. The current ADM1 release contains 77 administrative units. Selected polygons can be combined into a single study window for spatial filtering, mapping and point-pattern analysis. |\n\n### Data Wrangling and Quality Assessment\n\n#### Data import\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(sf, tidyverse, spatstat, tmap, knitr, rmarkdown)\n\n# Import accident records\naccidents <- read_csv(\"data/aspatial/thai_road_accident_2022.csv\")\n\n# Import administrative boundaries\nthailand_adm1 <- st_read(\n  \"data/geospatial/geoBoundaries-THA-ADM1.geojson\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `geoBoundaries-THA-ADM1' from data source \n  `/Users/muratkaya/Desktop/credor/ISSS626-GAA/Take-home_Ex/data/geospatial/geoBoundaries-THA-ADM1.geojson' \n  using driver `GeoJSON'\nSimple feature collection with 77 features and 5 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: 97.34381 ymin: 5.612851 xmax: 105.6368 ymax: 20.46483\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n```{.r .cell-code}\n# Inspect the imported data\nglimpse(accidents)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 20,843\nColumns: 17\n$ acc_code                    <dbl> 6566872, 6566880, 5706553, 5485750, 562445…\n$ incident_datetime           <chr> \"1.01.2022 00:01\", \"1.01.2022 00:01\", \"1.0…\n$ report_datetime             <chr> \"2.01.2022 11:45\", \"2.01.2022 11:44\", \"9.0…\n$ province_en                 <chr> \"Chai Nat\", \"Maha Sarakham\", \"Chumphon\", \"…\n$ agency                      <chr> \"department of rural roads\", \"department o…\n$ vehicle_type                <chr> \"motorcycle\", \"motorcycle\", \"private/passe…\n$ presumed_cause              <chr> \"driving under the influence of alcohol\", …\n$ accident_type               <chr> \"other\", \"other\", \"rollover/fallen on stra…\n$ number_of_vehicles_involved <dbl> 1, 1, 1, 1, 1, 1, 1, 1, 2, 3, 1, 1, 2, 1, …\n$ number_of_fatalities        <dbl> 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ number_of_injuries          <dbl> 1, 1, 0, 1, 2, 0, 1, 1, 2, 1, 1, 1, 1, 1, …\n$ weather_condition           <chr> \"clear\", \"dark\", \"clear\", \"clear\", \"clear\"…\n$ latitude                    <dbl> 15.113158, 16.489238, 10.625082, 7.934514,…\n$ longitude                   <dbl> 99.98124, 103.07762, 99.17715, 98.27715, 1…\n$ road_description            <chr> \"straight road\", \"straight road\", \"straigh…\n$ slope_description           <chr> \"no slope\", \"no slope\", \"no slope\", \"no sl…\n$ incident_time               <dttm> 2021-12-31 17:01:00, 2021-12-31 17:01:00,…\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(thailand_adm1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 77 features and 5 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: 97.34381 ymin: 5.612851 xmax: 105.6368 ymax: 20.46483\nGeodetic CRS:  WGS 84\nFirst 10 features:\n                    shapeName shapeISO                 shapeID shapeGroup\n1             Roi Et Province    TH-45 36821470B96343765829948        THA\n2             Phayao Province    TH-56 36821470B12194119812739        THA\n3       Nakhon Sawan Province    TH-60 36821470B58837026258254        THA\n4   Nong Bua Lam Phu Province    TH-39 36821470B48254980905782        THA\n5       Chachoengsao Province    TH-24 36821470B91271468807469        THA\n6              Surin Province    TH-32 36821470B33660676013176        THA\n7  Nakhon Ratchasima Province    TH-30 36821470B25997690360286        THA\n8          Sukhothai Province    TH-64 36821470B85895478064474        THA\n9        Phetchaburi Province    TH-76 36821470B90667358259218        THA\n10        Chaiyaphum Province    TH-36 36821470B61102131347890        THA\n   shapeType                       geometry\n1       ADM1 MULTIPOLYGON (((103.5111 16...\n2       ADM1 MULTIPOLYGON (((99.68719 19...\n3       ADM1 MULTIPOLYGON (((99.08899 15...\n4       ADM1 MULTIPOLYGON (((102.0808 17...\n5       ADM1 MULTIPOLYGON (((100.849 13....\n6       ADM1 MULTIPOLYGON (((103.4048 15...\n7       ADM1 MULTIPOLYGON (((101.4098 15...\n8       ADM1 MULTIPOLYGON (((99.31601 17...\n9       ADM1 MULTIPOLYGON (((99.20417 13...\n10      ADM1 MULTIPOLYGON (((102.3347 15...\n```\n\n\n:::\n:::\n\n\n#### Data inspection & cleaning\n\nInitial inspection examines variable types, missing values, duplicate records and the coordinate reference system.\n\nFirst, I exclude records from 2019–2021 and remove the province_th and route columns from the original downloaded csv. The remaining 2022 accident dataset contains 21,032 records and 16 variables. These two columns were removed because they contain Thai text, which I cannot read or understand.\n\nThen, I check for duplicate rows and remove any duplicates, retaining one copy of each row. I then identify rows with missing coordinates (latitude and/or longitude) and remove them.\n\nI then check for and remove invalid coordinates. Latitude must be between −90 and 90, and longitude between −180 and 180. is.finite() also excludes missing or infinite values.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Remove accidents occurring in 2019, 2020 and 2021\naccidents_clean <- accidents %>%\n  mutate(\n    incident_time = dmy_hm(incident_datetime, tz = \"Asia/Bangkok\")\n  ) %>%\n  filter(!(year(incident_time) %in% 2019:2021))\n\n# Count exact duplicate rows\nsum(duplicated(accidents_clean))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n\n```{.r .cell-code}\n# View exact duplicate rows\naccidents_clean[duplicated(accidents_clean), ]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 0 × 17\n# ℹ 17 variables: acc_code <dbl>, incident_datetime <chr>,\n#   report_datetime <chr>, province_en <chr>, agency <chr>, vehicle_type <chr>,\n#   presumed_cause <chr>, accident_type <chr>,\n#   number_of_vehicles_involved <dbl>, number_of_fatalities <dbl>,\n#   number_of_injuries <dbl>, weather_condition <chr>, latitude <dbl>,\n#   longitude <dbl>, road_description <chr>, slope_description <chr>,\n#   incident_time <dttm>\n```\n\n\n:::\n\n```{.r .cell-code}\n# Remove exact duplicates, keeping one copy\naccidents_clean <- accidents_clean %>%\n  distinct()\n\n# Confirm no exact duplicates remain\nsum(duplicated(accidents_clean))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n\n```{.r .cell-code}\n# Check whether there are any duplicate accident IDs\naccidents_clean %>%\n  count(acc_code) %>%\n  filter(n > 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 0 × 2\n# ℹ 2 variables: acc_code <dbl>, n <int>\n```\n\n\n:::\n\n```{.r .cell-code}\n# Identify rows missing latitude and/or longitude\nmissing_coordinates <- accidents_clean %>%\n  filter(is.na(latitude) | is.na(longitude))\n\n# Count these rows\nnrow(missing_coordinates)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n\n```{.r .cell-code}\n# Remove them, keeping rows with both coordinates\naccidents_clean <- accidents_clean %>%\n  filter(!is.na(latitude) & !is.na(longitude))\n\n# Identify invalid coordinates\ninvalid_coordinates <- accidents_clean %>%\n  filter(\n    !is.finite(latitude) | !is.finite(longitude) |\n      !between(latitude, -90, 90) |\n      !between(longitude, -180, 180)\n  )\n\n# Count and inspect affected rows\nnrow(invalid_coordinates)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n\n```{.r .cell-code}\ninvalid_coordinates\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 0 × 17\n# ℹ 17 variables: acc_code <dbl>, incident_datetime <chr>,\n#   report_datetime <chr>, province_en <chr>, agency <chr>, vehicle_type <chr>,\n#   presumed_cause <chr>, accident_type <chr>,\n#   number_of_vehicles_involved <dbl>, number_of_fatalities <dbl>,\n#   number_of_injuries <dbl>, weather_condition <chr>, latitude <dbl>,\n#   longitude <dbl>, road_description <chr>, slope_description <chr>,\n#   incident_time <dttm>\n```\n\n\n:::\n\n```{.r .cell-code}\n# Keep valid coordinates\naccidents_clean <- accidents_clean %>%\n  filter(\n    is.finite(latitude),\n    is.finite(longitude),\n    between(latitude, -90, 90),\n    between(longitude, -180, 180)\n  )\n\n# Save the cleaned data\nwrite_csv(accidents_clean, \"data/aspatial/thai_road_accident_2022.csv\")\n```\n:::\n\n\n## Task 2: First-Order Point-Pattern Analysis\n\nKernel Density Estimation (KDE) is used to examine how recorded accident intensity varies across the Bangkok Metropolitan Region (BMR). It converts accident locations into a continuous density surface, making concentrations easier to identify.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Select the six BMR provinces\nbmr <- thailand_adm1 %>%\n  filter(shapeISO %in% c(\n    \"TH-10\", \"TH-11\", \"TH-12\",\n    \"TH-13\", \"TH-73\", \"TH-74\"\n  )) %>%\n  st_transform(crs = 32647)\n\n# Convert the cleaned accident records into spatial points\naccidents_sf <- accidents_clean %>%\n  st_as_sf(\n    coords = c(\"longitude\", \"latitude\"),\n    crs = 4326\n  ) %>%\n  st_transform(crs = 32647)\n```\n:::\n\n\nConverting the data into the objects required by spatstat. The BMR boundary defines the observation window and only accidents inside it are retained.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Convert accidents into a point-pattern object\naccidents_ppp <- as.ppp(accidents_sf)\n\n# Define the study window\nbmr_owin <- as.owin(bmr)\n\n# Retain accidents within BMR\naccidents_bmr_ppp <- accidents_ppp[bmr_owin]\n\n# Analyse accident locations without attribute marks\naccidents_bmr_ppp <- unmark(accidents_bmr_ppp)\n\n# Change distance units from metres to kilometres\naccidents_bmr_km <- rescale.ppp(\n  accidents_bmr_ppp, 1000, \"km\"\n)\n\n# Inspect and plot the point pattern\nsummary(accidents_bmr_km)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPlanar point pattern:  3599 points\nAverage intensity 0.4732986 points per square km\n\n*Pattern contains duplicated points*\n\nCoordinates are given to 13 decimal places\n\nWindow: polygonal boundary\nsingle connected closed polygon with 1699 vertices\nenclosing rectangle: [587.1304, 712.4417] x [1484.7489, 1579.0872] km\n                     (125.3 x 94.34 km)\nWindow area = 7604.08 square km\nUnit of length: 1 km\nFraction of frame area: 0.643\n```\n\n\n:::\n\n```{.r .cell-code}\nplot(\n  accidents_bmr_km,\n  main = \"Recorded Road Accidents in BMR, 2022\"\n)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\n**Compute the density surface**\n\nUsing a Gaussian kernel with an automatically selected Diggle bandwidth. Rescaling the coordinates to kilometres makes the density values represent recorded accidents per square kilometre for 2022.\n\nKernel Density Estimation (KDE) is used to identify where recorded road accidents are concentrated within BMR. It transforms individual accident locations into a smooth surface showing estimated accidents per square kilometre during 2022.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Display the selected bandwidth in kilometres\nbw.diggle(accidents_bmr_km)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     sigma \n0.02307687 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Calculate KDE\nkde_diggle <- density(\n  accidents_bmr_km,\n  sigma = bw.diggle,\n  edge = TRUE,\n  kernel = \"gaussian\"\n)\n\n# Display the density map and its summary\nplot(\n  kde_diggle,\n  main = \"Accident Intensity in BMR, 2022\"\n)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n\n```{.r .cell-code}\nsummary(kde_diggle)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nreal-valued pixel image\n128 x 128 pixel array (ny, nx)\nenclosing rectangle: [587.1304, 712.4417] x [1484.749, 1579.087] km\ndimensions of each pixel: 0.979 x 0.7370174 km\nImage is defined on a subset of the rectangular grid\nSubset area = 7601.38225210896 square km\nSubset area fraction = 0.643\nPixel values (inside window):\n\trange = [-1.526474e-14, 88.69966]\n\tintegral = 3595\n\tmean = 0.4729403\n```\n\n\n:::\n:::\n\n\nThe bandwidth is selected automatically using bw.diggle. It controls the amount of smoothing: smaller bandwidths reveal local concentrations, while larger bandwidths show broader patterns. A Gaussian kernel gives nearby accidents greater influence than distant accidents.\n\nAreas with higher intensity contain greater concentrations of recorded accidents and may warrant closer road-safety investigation. Areas with lower intensity have fewer recorded accidents per unit area. These patterns describe accident concentration, rather than risk per road user, because traffic volume is not considered.\n\nThe KDE map shows uneven recorded accident intensity across BMR in 2022. The highest intensity appears along a short corridor in the southeastern part of the study area with additional concentrations extending through central and southern areas. Much of the western and northern area has lower intensity. The narrow, connected concentrations suggest a pattern associated with transport corridors.\n\n## Task 3: Second-Order Point-Pattern Analysis\n\n**Research question:** Do recorded accidents in BMR during 2022 show clustering or regularity at different distances compared with complete spatial randomness?\n\nThe L-function summarises neighbouring events across a range of distances. Plotting L(r) - r gives a theoretical reference of zero under complete spatial randomness. The simulation envelope helps assess whether departures exceed the variation expected.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\n\n# Randomly select up to 1,000 accidents\naccidents_sample <- accidents_bmr_km[\n  sample(\n    npoints(accidents_bmr_km),\n    min(1000, npoints(accidents_bmr_km))\n  )\n]\n\n# Calculate the L-function with 28 simulations\nL_accidents <- envelope(\n  accidents_sample,\n  Lest,\n  correction = \"Ripley\",\n  nsim = 28,\n  nrval = 100,\n  global = FALSE\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nGenerating 28 simulated realisations of CSR  ...\n1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,\n21, 22, 23, 24, 25, 26, 27, \n28.\n\nDone.\n```\n\n\n:::\n\n```{.r .cell-code}\nplot(\n  L_accidents, . - r ~ r,\n  main = \"BMR Accidents: Sampled L-function\",\n  xlab = \"Distance (km)\",\n  ylab = \"L(r) - r\"\n)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\nThe null model is complete spatial randomness (CSR). Under this model, accident locations are independent and equally likely throughout the BMR observation window.\n\nCSR provides a simple baseline for assessing spatial uniformity. However, it is a limited reference for road accidents because roads and traffic are unevenly distributed.\n\nThe analysis assumes that coordinates adequately represent accident locations and the BMR boundary defines the observation window. Distances are straight-line distances in kilometres. The conventional L-function uses a spatially homogeneous and directionally invariant reference.\n\n| Parameter | Explanation |\n|------------------------------------|------------------------------------|\n| `set.seed(1234)` | Makes the simulation reproducible. |\n| `correction = \"Ripley\"` | Adjusts for neighbours that cannot be observed beyond the study boundary. |\n| `nsim = 28` | Generates 28 simulated patterns under CSR. |\n| `rank = 1` | Uses the lowest and highest simulated values as envelope limits at each distance. |\n| `global = FALSE` | Produces a pointwise envelope, assessing each distance separately. |\n\nInterpreting the observed curve relative to the envelope:\n\n| Observed curve | Interpretation |\n|------------------------------------|------------------------------------|\n| Above the upper envelope | Evidence of clustering relative to CSR at those distances. |\n| Below the lower envelope | Evidence of regularity relative to CSR at those distances. |\n| Inside the envelope | No clear departure from CSR detected at those distances. This does not prove randomness. |\n\nThe observed L-function curve lies well above the upper CSR simulation envelope across almost all positive distances shown, up to approximately 23 km. This provides evidence of spatial clustering relative to complete spatial randomness in the sampled BMR accidents. There is no indication of regularity over this distance range.\n\nThe steep rise at short distances indicates an excess of nearby accident pairs compared with the uniform random reference. However, this pattern may reflect concentrations along roads and differences in traffic volume, rather than interaction between accidents.\n\n## Task 4: **Integration and Interpretation**\n\nThe first-order KDE analysis shows that recorded accidents are unevenly distributed across BMR. Higher intensity appears along narrow corridors, particularly in the southeastern area, while much of the western and northern area has lower intensity. The Gaussian kernel uses an automatically selected Diggle bandwidth and edge correction.\n\nThe second-order L-function analysis shows that the observed curve lies above the upper CSR simulation envelope across almost all positive distances displayed, up to approximately 23 km. This indicates clustering relative to complete spatial randomness, but does not establish interaction between accidents.\n\nThe findings are broadly consistent. KDE identifies where concentrations occur, while the L-function examines departures from a uniform random reference across distances. Road layout, traffic volume and reporting differences could explain both patterns without accidents influencing one another.\n\nSome limitations remain. KDE depends on bandwidth selection. The L-function uses a sample of up to 1,000 accidents and a pointwise simulation envelope, so sampling uncertainty and distance-specific interpretation must also be considered.\n\nAlternative explanations include the distribution of roads, traffic volume and reporting coverage.\n\n## Task 5: Geovisualisation and Analytical Interpretation\n\n### KDE map\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(\n  kde_diggle,\n  main = \"Recorded Accident Intensity in BMR, 2022\"\n)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\nThe KDE map suggests that recorded accidents are unevenly distributed across BMR. Brighter areas indicate higher estimated intensity, particularly along a short corridor in the southeastern area. Additional narrow concentrations appear through central and southern areas, while much of the western and northern area has lower intensity. Values represent estimated recorded accidents per square kilometre during 2022.\n\nHowever, the selected Diggle bandwidth of approximately 23 metres is much smaller than the default pixels, approximately 979 × 737 metres. The surface therefore does not adequately resolve this bandwidth, making local details and peak values unreliable. Concentrations also do not establish higher risk per road user because traffic exposure is unavailable.\n\n### L-function graph\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(\n  L_accidents, . - r ~ r,\n  main = \"BMR Accidents: Sampled L-function\",\n  xlab = \"Distance (km)\",\n  ylab = \"L(r) - r\"\n)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\nThe observed L-function curve lies well above the upper CSR simulation envelope across almost all positive distances displayed, extending to approximately 23 km. This indicates clustering relative to complete spatial randomness. The steep increase at short distances reflects an excess of nearby accident pairs compared with the uniform random reference. No evidence of regularity is apparent over the displayed range.\n\nThe analysis uses a random sample of up to 1,000 accidents, so results may vary with the sample. The envelope is pointwise and does not provide a global significance test. Road layout, uneven traffic exposure and reporting differences could explain the departure from CSR without interaction between accidents. The graph identifies distance scales of departure but does not locate specific accident hotspots.\n\n## Task 6: Public-Safety Planning and Management\n\nThe findings can support the initial identification of areas requiring closer road-safety investigation in BMR. The KDE map suggests concentrations of recorded accidents along narrow corridors, particularly in the southeastern area. The sampled L-function indicates clustering relative to complete spatial randomness across much of the examined distance range. These findings describe spatial patterns but do not establish their causes.\n\nFor transportation planning, the identified concentrations could guide the selection of locations for road-safety inspections. Authorities could investigate road conditions, junction design, lighting and traffic management at these locations. However, the analysis does not demonstrate that any of these factors caused the accidents.\n\nFor emergency response, the accident distribution could help identify areas where response coverage should be reviewed. Decisions about ambulance positioning or additional resources would require information on accident severity, existing facilities, travel times and service demand. The current analysis alone cannot determine suitable facility locations.\n\nFor resource allocation, areas with repeated recorded accidents could receive priority for further assessment. However, lower recorded intensity should not automatically justify reducing resources elsewhere. It may reflect lower traffic exposure, incomplete reporting or fewer but more severe accidents.\n\nThe results therefore support preliminary screening and further investigation. Traffic exposure, accident severity and reporting coverage are needed to assess risk and select appropriate interventions. As the analysis covers 2022, more recent records would also be needed for present-day planning.\n\n# Bonus: Value-Added Analysis\n\nThe additional research question is: Do the accident concentrations identified in the annual KDE remain in similar locations throughout 2022 or do they change between months?\n\nSpatio-temporal KDE extends the annual analysis by incorporating incident month. This is useful because an annual map can conceal changes in the geographic distribution of accidents. Persistent concentrations could identify locations for continuing road-safety investigation, while concentrations appearing in particular months would lead to investigation of temporary conditions.\n\nThe analysis examines changes in recorded accident distributions and does not establish their causes or higher risk per road user.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(sparr)\n\n# Use incident month as the point attribute\naccidents_month <- accidents_sf %>%\n  mutate(\n    incident_time = dmy_hm(\n      incident_datetime,\n      tz = \"Asia/Bangkok\"\n    ),\n    Month_num = month(incident_time)\n  ) %>%\n  select(Month_num) %>%\n  as.ppp()\n\n# Retain accidents inside BMR\naccidents_month <- accidents_month[bmr_owin]\n\n# Calculate spatio-temporal KDE\nmonthly_kde <- spattemp.density(accidents_month)\n\n# Inspect bandwidths and observation period\nsummary(monthly_kde)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSpatiotemporal Kernel Density Estimate\n\nBandwidths\n  h = 4882.467 (spatial)\n  lambda = 0.0285 (temporal)\n\nNo. of observations\n  3599 \n\nSpatial bound\n  Type: polygonal\n  2D enclosure: [587130.4, 712441.7] x [1484749, 1579087]\n\nTemporal bound\n  [1, 12]\n\nEvaluation\n  128 x 128 x 12 trivariate lattice\n  Density range: [9.448582e-22, 2.845214e-09]\n```\n\n\n:::\n\n```{.r .cell-code}\n# Display all months using a common colour scale\nfor (i in 1:12) {\n  plot(\n    monthly_kde, i,\n    override.par = TRUE,\n    fix.range = TRUE,\n    main = paste(\"BMR Accidents, 2022: Month\", i)\n  )\n}\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-9-2.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-9-3.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-9-4.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-9-5.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-9-6.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-9-7.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-9-8.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-9-9.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-9-10.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-9-11.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-9-12.png){width=672}\n:::\n:::\n\n\nThe monthly maps show recurring accident concentrations in central and southeastern BMR, while western areas generally have lower estimated density. Using the shared colour scale, January and December show more prominent concentrations than February. December displays a particularly strong southeastern concentration.\n\nThis extends the annual analysis by showing that broadly similar locations remain prominent, while the strength and extent of concentrations vary between months. These patterns could guide continuing road-safety investigation and closer examination of January and December.\n\nThe analysis includes 3,599 accidents. The automatically selected spatial bandwidth is approximately 4.88 km, while the temporal bandwidth is 0.0285 months. This provides little smoothing between months, so the maps primarily show monthly differences. One year of observations cannot establish recurring seasonality, and traffic exposure would be needed to assess risk per road user.\n",
    "supporting": [
      "Take-home_Ex01_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}